language: node_js

node_js:
  - "4"
  - "6"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master

script:
  - yarn test

after_success:
  - $(yarn bin)/nyc report --reporter=text-lcov | $(yarn bin)/coveralls
